name: test reuse

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - "main"

jobs:
  number1:
    name: number1
    runs-on: ubuntu-latest
    timeout-minutes: 70
    steps:

        - name: Install SSH key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.BORS }}
            known_hosts: ${{ secrets.KNOWN_HOSTS }}

        - uses: actions/checkout@v2

        - run: mkdir -p artifact_test

        - run: echo hello > artifact_test/world.txt
        - run: echo helloe > artifact_test/worlde.txt

        - uses: actions/upload-artifact@v2
          with:
            name: artifact_test
            path: artifact_test/world.txt

        - name: Get current branch
          shell: bash
          run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          id: current_branch

        - name: copy repo
          shell: bash
          run: |
            # Create a temporary folder to clone the other repo
            CLONE_DIR=$(mktemp -d)
            DST_REPO='abargiela/test_bors_ng_v1'
            EMAIL='ci@project.io'
            USERNAME='ci'
            BRANCH=${{ steps.current_branch.outputs.branch }}
            SRC_COMMIT=$(git rev-parse HEAD)
            
            # Set the key to be able to clone the repo
            git config --global user.email $EMAIL
            git config --global user.name $USERNAME
             # cloning the destination repo
            BRANCH_EXISTS=$(git ls-remote --heads "git@github.com:$DST_REPO.git" $BRANCH | wc -l);
            if [ $BRANCH_EXISTS -eq 0 ];then
              git clone --depth 1 "git@github.com:$DST_REPO.git" $CLONE_DIR
              cd $CLONE_DIR
            else
              git clone -b $BRANCH --depth 1 "git@github.com:$DST_REPO.git" $CLONE_DIR;
              cd $CLONE_DIR
            fi
            # Cleaning all files on the destination repository
            git rm -r .
            # Copy all files from the src repo to the dst repo
            cd - ;
            rsync -avz * .gitignore  $CLONE_DIR \
              --exclude '.git' \
              --exclude '.github';
            cd $CLONE_DIR
            git add -A;
            # If anything is modified is commited
            git status --porcelain | wc -l
            if [ $(git status --porcelain | wc -l) -gt 0 ]; then
            git commit --message " $(git log --format=%B -n1)
                                  https://github.com/commit/$SRC_COMMIT
                                  https://github.com/tree/$BRANCH"
                git push -u origin HEAD:$BRANCH
            fi
